Refs: #19 - check for aws cli tool in evon_standalone_hook_example

diff --git a/evon/evon_standalone_hook_example b/evon/evon_standalone_hook_example
--- a/evon/evon_standalone_hook_example
+++ b/evon/evon_standalone_hook_example
@@ -106,6 +106,12 @@ function delete_record() {
 logit "evon_standalone_hook starting..."
 logit "env: endpoint='$endpoint' method='$method' headers='$headers' body='$body' params='$params'"
 
+if [ ! $(which aws >/dev/null 2>&1) ]; then
+    echo "ERROR: This script requires the 'aws' command to be present and configured on this system."
+    echo "       To fix this issue, edit file: $0"
+    exit 1
+fi
+
 if [ "$endpoint" == "/api/zone/records" ]; then
 
     if [ "$EVON_HOOK_REQUEST_METHOD" == "put" ]; then
